### PR TITLE
Add uml diagrams and update DG

### PR DESCRIPTION
**Pull request by jishnu28**

### CODE REVIEW

**Comment by wxxedu** [comment]
Will need to remove a couple of white spaces before this can be merged.

**Comment by BoAi01** [comment]
There is some format issues here that fail the CI test. Shall we resolve them first?

**Comment by jishnu28** [comment]
> There is some format issues here that fail the CI test. Shall we resolve them first?

Fixed them! Thanks for reminding!

**Review by tangyuantyy — APPROVED** [review]
LGTM

**Pull request merged**
