### PR TITLE
Wrap text for item information

### PR DESCRIPTION
**Pull request by tangyuantyy**
fix [Suggestion : Can use text wrap for long names #202](https://github.com/AY2223S2-CS2103T-W11-1/tp/issues/202)

### CODE REVIEW

**Review by cetigerlily — APPROVED** [review]
LGTM!

**Comment by wxxedu** [comment]
Sorry that I just had a look at this. I am a bit worried about whether this is a feature flaw that we were going to fix. (Coz it's not a bug), and we are not really allowed to change much about the UI.

**Review by wxxedu — CHANGES_REQUESTED** [review]
Confirm if we could fix this.

**Comment by jishnu28** [comment]
You're right @wxxedu seems like we won't be allowed to make this change cos the mod website says 

" ❌  any UI changes (even purely cosmetic enhancements e.g., alignments, style changes are not allowed)."

**Comment by tangyuantyy** [comment]
Ok sure I can close this PR, but just to check, even if it is picked out as feature flaw, we cannot make any changes to it?

**Comment by wxxedu** [comment]
I doubt we can.

**Comment by wxxedu** [comment]
I don't think that this is a feature flaw though :-)

**Pull request closed without merging**
