### PR TITLE
Migrate doc from Google Docs to Markdown

### PR DESCRIPTION
**Pull request by wxxedu**
As stated in the prompt.

I also updated the design of the documentation so that we will be using a `modal` design.

### CODE REVIEW

**Comment by wxxedu** [comment]
@tangyuantyy do you mind having a look at this and merge this PR?

**Review by tangyuantyy — COMMENTED** [review]
LGTM

**Comment by wxxedu** [comment]
I think we may need to fix the space issue in Markdown styling.

**Review by tangyuantyy — COMMENTED** [review]
lgtm

**Review by tangyuantyy — APPROVED** [review]
lgtm

**Pull request merged**
