### PR TITLE
Remove addressbook related code

### PR DESCRIPTION
**Pull request by jishnu28**
Removed most of the AB3 code.

Did not remove person and tag-related classes because the Ui classes "PersonCard" and "PersonListPanel" had multiple usages of them and any removal I did affected the display for our 5 classes. So I've left these classes in for now.

Current PR also works just as before on my end, with regard to adding and deleting in all 5 classes so should have no issues!

### CODE REVIEW

**Review by wxxedu — COMMENTED** [review]
LGTM, some else may also have a look?

**Comment by wxxedu** [comment]
Forgot to read your comment, I think these classes can be safely removed (just remove the equivalent usages in the UI layer). We are not using them currently in the UI.

**Comment by jishnu28** [comment]
> Forgot to read your comment, I think these classes can be safely removed (just remove the equivalent usages in the UI layer). We are not using them currently in the UI.

Should I also remove the stuff in the docs folder that are about AB3? Things like AddRemark.md and diagrams.

**Comment by tangyuantyy** [comment]
I think we don't have to remove the docs and we can keep them as reference.

**Review by tangyuantyy — APPROVED** [review]
LGTM!

**Comment by jishnu28** [comment]
> I think we don't have to remove the docs and we can keep them as reference.

Ok, I've kept the docs and just removed the files related to 'person' and 'tag'

**Pull request merged**
