### PR TITLE
Fix unaligned documentation

### PR DESCRIPTION
**Pull request by tangyuantyy**
fix [https://github.com/AY2223S2-CS2103T-W11-1/tp/issues/220](url)

### CODE REVIEW

**Review by cetigerlily — APPROVED** [review]
LGTM!

**Comment by BoAi01** [comment]
There are two conflicts here, but I am not sure which parts to keep.

**Comment by jishnu28** [comment]
I realise the changes to other files besides the UG in this PR is the same as #237 . Which @wxxedu was right about, that we weren't allowed to make this change. Besides that, once the merge conflicts are settled, I think we can merge this PR

**Comment by wxxedu** [comment]
> How can I merge only one of the commits out of the four?

You can locally revert the other commits :-)

**Review by wxxedu — CHANGES_REQUESTED** [review]
In your local git, revert the other changes that are irrelevant, and then resubmit this pull request. If any problem, let me know.

**Pull request closed without merging**
